esphome:
  name: esp32-s3-n16r8-001
  friendly_name: ESP32-S3-N16R8-001
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  #variant: esp32s3
  flash_size: 16MB
  framework:
    #type: arduino
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # Need to set a s3 compatible board for the adf-sdk to compile
      # board specific code is not used though
      CONFIG_ESP32_S3_BOX_BOARD: "y"

# Enable logging
logger:
  #hardware_uart: uart0
  #level: VERBOSE

psram:
  mode: octal
  speed: 80MHz

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key010

ota:
  password: !secret ota_pass010

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password
  use_address: !secret use_address_wifi010
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32-S3-N16R8-01FallbackHotspot"
    password: !secret fallbackhotspot010

captive_portal:

web_server:

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 7
  id: uart_bus
  debug:
    direction: BOTH
    dummy_receiver: true
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ':');
      - lambda: if (direction == uart::UART_DIRECTION_RX) id(get_status).publish_state(format_hex_pretty(bytes));
      - lambda: >
          if (direction == uart::UART_DIRECTION_RX) {
            // The get status hex should be 16 bits long
            if (bytes.size() == 16) {
              // Power State
              // 03.0C.F1.03.0C.F5.08.F0.00.00.00.F1.05.00.00.0E (16)
              if (bytes[8] == 0x00) {
                if (bytes[12] == 0x05) {
                  id(power_status).publish_state("On");
                } else if (bytes[12] == 0x04) {
                  id(power_status).publish_state("Stand-By");
                } else if (bytes[12] == 0x08) {
                  id(power_status).publish_state("Off");
                }
              // Volume Status
              // 03.0C.F1.03.0C.F5.08.F0.01.00.00.F1.07.00.00.0B (16)
              } else if (bytes[8] == 0x01) {
                id(volume_status).publish_state(bytes[12]);
              // Mute Status
              } else if (bytes[8] == 0x02) {
                if (bytes[12] == 0x00) {
                  id(mute_status).publish_state("Off");
                } else if (bytes[12] == 0x01) {
                  id(mute_status).publish_state("On");
              }
              // Channel Status
              //                                     Channel/Major/Minor (x12=18,x01=1,x02=2)
              // 03.0C.F1.03.0C.F5.08.F0.03.00.00.F1.12.01.02.FB (16)
              } else if (bytes[8] == 0x03) {
                uint8_t channelprimary = bytes[12];
                uint8_t channelmajor = bytes[13];
                uint8_t channelminor = bytes[14];
                id(channel_status).publish_state(to_string(channelprimary)+"-"+to_string(channelmajor)+"-"+to_string(channelminor));
              // Source Status
              } else if (bytes[8] == 0x04) {
                // 03.0C.F1.03.0C.F5.08.F0.04.00.00.F1.00.00.00.0F (16)
                if (bytes[12] == 0x00) {
                  id(source_status).publish_state("TV");
                // 03.0C.F1.03.0C.F5.08.F0.04.00.00.F1.39.00.00.D6 (16)
                } else if (bytes[12] == 0x39) {
                  id(source_status).publish_state("HDMI1");
                // 03.0C.F1.03.0C.F5.08.F0.04.00.00.F1.3A.00.00.D5 (16)
                } else if (bytes[12] == 0x3A) {
                  id(source_status).publish_state("HDMI2");
                // 03.0C.F1.03.0C.F5.08.F0.04.00.00.F1.1C.00.00.F3 (16)
                } else if (bytes[12] == 0x1C) {
                  id(source_status).publish_state("AV1");
                // 03.0C.F1.03.0C.F5.08.F0.04.00.00.F1.29.00.00.E6 (16)
                } else if (bytes[12] == 0x29) {
                  id(source_status).publish_state("Component1");
                }
              }
            }
          }

text_sensor:
  - platform: template
    id: "get_status"
    name: "Get Status"
  - platform: template
    id: "power_status"
    name: "Power Status"
  - platform: template
    id: "source_status"
    name: "Source Status"
  - platform: template
    id: "channel_status"
    name: "Channel Status"

sensor:
  - platform: template
    id: "volume_status"
    name: "Volume Status"
    accuracy_decimals: 0

binary_sensor:
  - platform: template
    id: "mute_status"
    name: "Mute Status"

button:
  - platform: restart
    name: "Restart"
    id: but_rest
  - platform: uart
    uart_id: uart_bus
    name: "Power Toggle"
    data: [0x08, 0x22, 0x00, 0x00, 0x00, 0x00, 0xD6]
  - platform: uart
    uart_id: uart_bus
    name: "Power On" # 08 22 00 00 00 02 D4
    data: [0x08, 0x22, 0x00, 0x00, 0x00, 0x02, 0xD4]
  - platform: uart
    uart_id: uart_bus
    name: "Power Off"
    data: [0x08, 0x22, 0x00, 0x00, 0x00, 0x01, 0xD5]
  - platform: uart
    uart_id: uart_bus
    name: "Volume Up"
    data: [0x08, 0x22, 0x01, 0x00, 0x01, 0x00, 0xD4]
  - platform: uart
    uart_id: uart_bus
    name: "Volume Down"
    data: [0x08, 0x22, 0x01, 0x00, 0x02, 0x00, 0xD3]
  - platform: uart
    uart_id: uart_bus
    name: "Mute"
    data: [0x08, 0x22, 0x02, 0x00, 0x00, 0x00, 0xD4]
  - platform: uart
    uart_id: uart_bus
    name: "TV"
    data: [0x08, 0x22, 0x0A, 0x00, 0x00, 0x00, 0xCC]
  - platform: uart
    uart_id: uart_bus
    name: "HDMI 1"
    data: [0x08, 0x22, 0x0A, 0x00, 0x05, 0x00, 0xC7]
  - platform: uart
    uart_id: uart_bus
    name: "HDMI 2"
    data: [0x08, 0x22, 0x0A, 0x00, 0x05, 0x01, 0xC6]
  - platform: uart
    uart_id: uart_bus
    name: "AV1"
    data: [0x08, 0x22, 0x0A, 0x00, 0x01, 0x00, 0xCB]
  - platform: uart
    uart_id: uart_bus
    name: "Component1"
    data: [0x08, 0x22, 0x0A, 0x00, 0x03, 0x00, 0xC9]
  - platform: uart
    uart_id: uart_bus
    name: "Source - Smart Hub"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x79, 0x50]
  - platform: uart
    uart_id: uart_bus
    name: "Source - Netflix"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0xD7, 0xF2]
  - platform: uart
    uart_id: uart_bus
    name: "Source - Prime"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0xD6, 0xF3]
  - platform: uart
    uart_id: uart_bus
    name: "Source - YouTube"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0xD8, 0xF1]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 1"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x04, 0xC5]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 2"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x05, 0xC4]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 3"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x06, 0xC3]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 4"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x08, 0xC1]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 5"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x09, 0xC0]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 6"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x0A, 0xBF]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 7"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x0C, 0xBD]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 8"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x0D, 0xBC]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 9"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x0E, 0xBB]
  - platform: uart
    uart_id: uart_bus
    name: "Digit 0"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x11, 0xB8]
  - platform: uart
    uart_id: uart_bus
    name: "Digit -"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x23, 0xA6]
  - platform: uart
    uart_id: uart_bus
    name: "Channel Up"
    data: [0x08, 0x22, 0x03, 0x00, 0x01, 0x00, 0xD2]
  - platform: uart
    uart_id: uart_bus
    name: "Channel Down"
    data: [0x08, 0x22, 0x03, 0x00, 0x02, 0x00, 0xD1]
  - platform: uart
    uart_id: uart_bus
    # 10-1
    name: "Channel1"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x0A, 0xC8]
  - platform: uart
    uart_id: uart_bus
    # 14-3
    name: "Channel2"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x0E, 0xC4]
  - platform: uart
    uart_id: uart_bus
    # 18-1
    name: "Channel3"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x12, 0xC0]
  - platform: uart
    uart_id: uart_bus
    # 19-1
    name: "Channel4"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x13, 0xBF]
  - platform: uart
    uart_id: uart_bus
    # 20-1
    name: "Channel5"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x14, 0xBE]
  - platform: uart
    uart_id: uart_bus
    # 31-1
    name: "Channel6"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x01F, 0xB3]
  - platform: uart
    uart_id: uart_bus
    # 69-1
    name: "Channel7"
    data: [0x08, 0x22, 0x04, 0x00, 0x00, 0x45, 0x8D]
  - platform: uart
    uart_id: uart_bus
    name: "Input Source Toggle"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x01, 0xC8]
  - platform: uart
    uart_id: uart_bus
    name: "Previous Channel"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x13, 0xB6]
  - platform: uart
    uart_id: uart_bus
    name: "Channel List"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x6B, 0x5E]
  - platform: uart
    uart_id: uart_bus
    name: "Guide"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x4F, 0x7A]
  - platform: uart
    uart_id: uart_bus
    name: "Tools"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x1F, 0xAA]
  - platform: uart
    uart_id: uart_bus
    name: "Info Display"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x1F, 0xAA]
  - platform: uart
    uart_id: uart_bus
    name: "Menu"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x1A, 0xAF]
  - platform: uart
    uart_id: uart_bus
    name: "Up"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x60, 0x69]
  - platform: uart
    uart_id: uart_bus
    name: "Down"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x61, 0x68]
  - platform: uart
    uart_id: uart_bus
    name: "Right"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x62, 0x67]
  - platform: uart
    uart_id: uart_bus
    name: "Left"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x65, 0x64]
  - platform: uart
    uart_id: uart_bus
    name: "Enter OK"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x68, 0x61]
  - platform: uart
    uart_id: uart_bus
    name: "Return Back"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x58, 0x17]
  - platform: uart
    uart_id: uart_bus
    name: "Exit"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x2D, 0x9C]
  - platform: uart
    uart_id: uart_bus
    name: "Red"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x6C, 0x5D]
  - platform: uart
    uart_id: uart_bus
    name: "Green"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x14, 0xB5]
  - platform: uart
    uart_id: uart_bus
    name: "Yellow"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x15, 0xB4]
  - platform: uart
    uart_id: uart_bus
    name: "Blue"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x16, 0xB3]
  - platform: uart
    uart_id: uart_bus
    name: "Picture Size"
    data: [0x08, 0x22, 0x0B, 0x0A, 0x01, 0x05, 0xBB]
  - platform: uart
    uart_id: uart_bus
    name: "E-Manual"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x3F, 0x8A]
  - platform: uart
    uart_id: uart_bus
    name: "Search"
    #data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x93, 0x36]
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x73, 0x56]
  - platform: uart
    uart_id: uart_bus
    name: "Keypad"
    data: [0x08, 0x22, 0x0B, 0x0A, 0x01, 0x05, 0xBB]
  - platform: uart
    uart_id: uart_bus
    name: "MTS"
    #data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x2B, 0x9E]
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x00, 0xC9]
  - platform: uart
    uart_id: uart_bus
    name: "Caption"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x25, 0xA4]
  - platform: uart
    uart_id: uart_bus
    name: "STB"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0xE0, 0xE9]
  - platform: uart
    uart_id: uart_bus
    name: "Play"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x47, 0x82]
  - platform: uart
    uart_id: uart_bus
    name: "Pause"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x4A, 0x7F]
  - platform: uart
    uart_id: uart_bus
    name: "Stop"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x46, 0x83]
  - platform: uart
    uart_id: uart_bus
    name: "Rewind"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x45, 0x84]
  - platform: uart
    uart_id: uart_bus
    name: "Fast Forward"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x48, 0x81]
  - platform: uart
    uart_id: uart_bus
    name: "Skip Back"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x50, 0x79]
  - platform: uart
    uart_id: uart_bus
    name: "Skip Forward"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x4E, 0x7B]
  - platform: uart
    uart_id: uart_bus
    name: "Record"
    data: [0x08, 0x22, 0x0D, 0x00, 0x00, 0x49, 0x80]
# Get Command:
# TV Reaction
# Success / Fail _F1_ _Success_
# Data Length    _8_
# Command        _F0_ _0_ _0_ _0_
# Data Value     _5_ _0_ _0_
# Category       _Power_
# Current State  _Normal Mode_
  - platform: uart
    uart_id: uart_bus
    name: "Power Get"
    data: [0x08, 0x22, 0xF0, 0x00, 0x00, 0x00, 0xE6]
  - platform: uart
    uart_id: uart_bus
    name: "Volume Get"
    data: [0x08, 0x22, 0xF0, 0x01, 0x00, 0x00, 0xE5]
  - platform: uart
    uart_id: uart_bus
    name: "Mute Get"
    data: [0x08, 0x22, 0xF0, 0x02, 0x00, 0x00, 0xE4]
  - platform: uart
    uart_id: uart_bus
    name: "Channel Get"
    data: [0x08, 0x22, 0xF0, 0x03, 0x00, 0x00, 0xE3]
  - platform: uart
    uart_id: uart_bus
    name: "Source Get"
    data: [0x08, 0x22, 0xF0, 0x04, 0x00, 0x00, 0xE2]
